#!/bin/bash

## Copyright (c) 2015 Adam Solesby -- see MIT LICENSE

## This script gathers the most recent 5 screenshots from the simulator (stored on ~/Desktop)
## and renames them sequentially (newest is screen5; oldest is screen1)
## It moves them into the named templates directory

## TODO: take 5 as optional command line param


if [ "$#" -eq 0 ] ; then
    echo "Usage: $0 <destination>"
    exit
fi

files=`ls -t ~/Desktop/Simulator*png | head -5`

i=`echo "$files"|wc -l`
let "i -= 0"


echo "Gathering $i files"
echo "$files"

DEST="$1"

if [ -e "screenshots" ] ; then
	DEST="screenshots/${DEST}"
fi

echo " moving to ${DEST}"
mkdir -p "${DEST}"

IFS=$'\n'
for f in $files ; do
    mv "$f" "${DEST}/screen${i}.png"
	file "${DEST}/screen${i}.png"
    let "i -= 1"
done


